### ISSUE TITLE
How about entity relations ?

### ISSUE THREAD

**Issue by dunsunik** [rlemaigre/JMiniORM#2]
Your ORM looks really nice but how about ManyToOne, OneToMany, ManyToMany relations ?
Are they supported ?
Thanks

**Comment by rlemaigre** [comment]
Hello, thank you for your interest in the project.

Relationships are not supported (well they are, sort of, see next paragraph). I don't plan to add support for this. It seems to me that it would defeat the purpose of this project : to be lightweight, flexible and simple to learn. If you need a full featured ORM that imposes its own way of doing this to you, use Hibernate or similar solutions.

However, it is not difficult for clients of the project to implement relationships just the way they like it. OneToMany and ManyToOne relationships can be edited using an entity property to store the foreign key, and accessed using a simple ORM query with whatever ordering, limit and offset you need. ManyToMany relationships can be modeled as entities and edited with delete, update and insert queries.

I haven't yet had the opportunity to try this, but a colleague of mine did it successfully so it's definitely possible.
